### ISSUE TITLE
Is there going to be any license for this project?

### ISSUE THREAD

**Issue by Mr-Dai** [HearthSim/Brazier#4]
I have been reading the source code of this project and find it perfectly suitable for my project. Perhaps I'm going to use this project in my project, and when I say "use" I mean copying the source code into my project and doing further modifications, instead of just using it as a jar dependency.

So, I'm wondering if there is going to be any license for me to check?

**Comment by kelemen** [comment]
I don't care how you use this project. Consider this in the public domain.

**Comment by Mr-Dai** [comment]
Thanks for the reply.

Last question: I really like this project and plan to contribute. So far, the modifications I made include minor refactoring and documenting. Is there anything I should notice or watch out for before I send any pull request?

**Comment by kelemen** [comment]
I generally use standard Java conventions and also I would prefer no tabs and LF as a line ending but otherwise I will comment on the PR if there is anything else.

**Comment by Mr-Dai** [comment]
I see. Thanks bro.
